/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-07-05 07:00:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blank_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>图书管理系统-主页</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\"\n");
      out.write("\tcontent=\"Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.\">\n");
      out.write("<meta name=\"author\" content=\"Muhammad Usman\">\n");
      out.write("\n");
      out.write("<!-- The styles -->\n");
      out.write("<link id=\"bs-css\" href=\"css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link href=\"css/charisma-app.css\" rel=\"stylesheet\">\n");
      out.write("<link href='bower_components/fullcalendar/dist/fullcalendar.css'\n");
      out.write("\trel='stylesheet'>\n");
      out.write("<link href='bower_components/fullcalendar/dist/fullcalendar.print.css'\n");
      out.write("\trel='stylesheet' media='print'>\n");
      out.write("<link href='bower_components/chosen/chosen.min.css' rel='stylesheet'>\n");
      out.write("<link href='bower_components/colorbox/example3/colorbox.css'\n");
      out.write("\trel='stylesheet'>\n");
      out.write("<link href='bower_components/responsive-tables/responsive-tables.css'\n");
      out.write("\trel='stylesheet'>\n");
      out.write("<link\n");
      out.write("\thref='bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css'\n");
      out.write("\trel='stylesheet'>\n");
      out.write("<link href='css/jquery.noty.css' rel='stylesheet'>\n");
      out.write("<link href='css/noty_theme_default.css' rel='stylesheet'>\n");
      out.write("<link href='css/elfinder.min.css' rel='stylesheet'>\n");
      out.write("<link href='css/elfinder.theme.css' rel='stylesheet'>\n");
      out.write("<link href='css/jquery.iphone.toggle.css' rel='stylesheet'>\n");
      out.write("<link href='css/uploadify.css' rel='stylesheet'>\n");
      out.write("<link href='css/animate.min.css' rel='stylesheet'>\n");
      out.write("\n");
      out.write("<!-- The fav icon -->\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/favicon.ico\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<!-- topbar starts -->\n");
      out.write("\t<div class=\"navbar navbar-default\" role=\"navigation\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"navbar-inner\">\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle pull-left animated flip\">\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.html\"> <img\n");
      out.write("\t\t\t\talt=\"Charisma Logo\" src=\"img/logo20.png\" class=\"hidden-xs\" /> <span>图书管理系统</span></a>\n");
      out.write("\n");
      out.write("\t\t\t<!-- user starts -->\n");
      out.write("\t\t\t<div class=\"btn-group pull-right\">\n");
      out.write("\t\t\t\t<ul class=\"collapse navbar-collapse nav navbar-nav top-menu\">\n");
      out.write("\t\t\t\t\t<li><a href=\"\"><i class=\"glyphicon glyphicon-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUserName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"load_modify_pwd\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i>修改密码</a>\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i>退出登录</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- user ends -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- topbar ends -->\n");
      out.write("\n");
      out.write("\t<div class=\"ch-container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- left menu starts -->\n");
      out.write("\t\t\t<div class=\"col-sm-2 col-lg-2\">\n");
      out.write("\t\t\t\t<div class=\"sidebar-nav\">\n");
      out.write("\t\t\t\t\t<div class=\"nav-canvas\">\n");
      out.write("\t\t\t\t\t\t<div class=\"nav-sm nav nav-stacked\"></div>\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-pills nav-stacked main-menu\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-header\">功能</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"load_blank\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t主页</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-header hidden-md\">系统管理模块</li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"manage_user\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t系统用户管理</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"manage_reader_type\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t读者类别管理</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"manage_reader\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t读者信息管理</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"manage_publisher\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t出版社管理</span></a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-header hidden-md\">图书借阅模块</li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"book\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t图书信息管理</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"book_borrow\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t图书借阅管理</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"accordion\"><a href=\"book_return\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t图书归还管理</span></a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-header hidden-md\">查询模块</li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"check_book\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t图书借阅情况查询</span></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"check_reader\"><span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t读者借阅情况查询</span></a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--/span-->\n");
      out.write("\t\t\t<!-- left menu ends -->\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"content\" class=\"col-lg-10 col-sm-10\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<ul class=\"breadcrumb\">\n");
      out.write("\t\t\t\t\t\t<li>主页</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"box col-md-12\">\n");
      out.write("\t\t\t\t\t\t<div class=\"box-inner\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-header well\" data-original-title=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<h2>主页</h2>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box-content\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"well col-md-5 center login-box\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"alert alert-info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${returnMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<hr>\n");
      out.write("\n");
      out.write("\t\t\t\t<footer class=\"row\">\n");
      out.write("\t\t\t\t<p class=\"col-md-9 col-sm-9 col-xs-12 copyright\">&copy; 图书管理系统\n");
      out.write("\t\t\t\t\t柯思佳</p>\n");
      out.write("\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
