/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2017-07-05 06:58:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>图书管理系统-登录</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.\">\r\n");
      out.write("<meta name=\"author\" content=\"Muhammad Usman\">\r\n");
      out.write("\r\n");
      out.write("<!-- The styles -->\r\n");
      out.write("<link id=\"bs-css\" href=\"css/bootstrap-cerulean.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/charisma-app.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href='bower_components/fullcalendar/dist/fullcalendar.css'\r\n");
      out.write("\trel='stylesheet'>\r\n");
      out.write("<link href='bower_components/fullcalendar/dist/fullcalendar.print.css'\r\n");
      out.write("\trel='stylesheet' media='print'>\r\n");
      out.write("<link href='bower_components/chosen/chosen.min.css' rel='stylesheet'>\r\n");
      out.write("<link href='bower_components/colorbox/example3/colorbox.css'\r\n");
      out.write("\trel='stylesheet'>\r\n");
      out.write("<link href='bower_components/responsive-tables/responsive-tables.css'\r\n");
      out.write("\trel='stylesheet'>\r\n");
      out.write("<link\r\n");
      out.write("\thref='bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css'\r\n");
      out.write("\trel='stylesheet'>\r\n");
      out.write("<link href='css/jquery.noty.css' rel='stylesheet'>\r\n");
      out.write("<link href='css/noty_theme_default.css' rel='stylesheet'>\r\n");
      out.write("<link href='css/elfinder.min.css' rel='stylesheet'>\r\n");
      out.write("<link href='css/elfinder.theme.css' rel='stylesheet'>\r\n");
      out.write("<link href='css/jquery.iphone.toggle.css' rel='stylesheet'>\r\n");
      out.write("<link href='css/uploadify.css' rel='stylesheet'>\r\n");
      out.write("<link href='css/animate.min.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("<!-- The fav icon -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"ch-container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 center login-header\">\r\n");
      out.write("\t\t\t\t\t<h2>欢迎来到图书管理系统</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/span-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/row-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"well col-md-5 center login-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${returnMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&nbsp&nbsp&nbsp请输入账号和密码</div>\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\" action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user red\"></i></span> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"账号\" name=\"userId\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group input-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock red\"></i></span> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" class=\"form-control\" placeholder=\"密码\" name=\"pwd\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"remember\" for=\"remember\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"checkbox\" id=\"remember\"> 记住我</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"center col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">登录</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--/span-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--/row-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--/fluid-row-->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--/.fluid-container-->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
